# Generated by Django 5.2.10 on 2026-01-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram User ID')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Message ID')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram File ID')),
                ('resume_text', models.TextField(verbose_name='Текст резюме')),
                ('roast_result', models.TextField(blank=True, null=True, verbose_name='Результат прожарки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Обработка резюме',
                'verbose_name_plural': 'Обработки резюме',
                'ordering': ['-created_at'],
            },
        ),
    ]
